__main__ - optimizer_entrypoint(line:879) - !!! Skip optimizer !!! root_node_rps of all callgraph in all region is 0
__main__ - optimizer_entrypoint(line:879) - !!! Skip optimizer !!! root_node_rps of all callgraph in all region is 0
__main__ - optimizer_entrypoint(line:879) - !!! Skip optimizer !!! root_node_rps of all callgraph in all region is 0
__main__ - optimizer_entrypoint(line:879) - !!! Skip optimizer !!! root_node_rps of all callgraph in all region is 0
__main__ - optimizer_entrypoint(line:879) - !!! Skip optimizer !!! root_node_rps of all callgraph in all region is 0
__main__ - optimizer_entrypoint(line:879) - !!! Skip optimizer !!! root_node_rps of all callgraph in all region is 0
__main__ - optimizer_entrypoint(line:879) - !!! Skip optimizer !!! root_node_rps of all callgraph in all region is 0
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-08 06:10:23 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 953, in optimizer_entrypoint
    weight = flow / total
ZeroDivisionError: division by zero
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-08 06:10:24 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 953, in optimizer_entrypoint
    weight = flow / total
ZeroDivisionError: division by zero
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-08 06:10:25 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 953, in optimizer_entrypoint
    weight = flow / total
ZeroDivisionError: division by zero
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-08 06:10:36 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-08 06:11:14 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1006, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - verify_return_df(line:344) - ERROR: weight is out of range. 3.9473684210526314
__main__ - verify_return_df(line:345) - row: src_svc                    frontend
dst_svc                           a
src_endpoint    frontend@GET@/start
dst_endpoint        a@POST@/spreada
src_cid                   us-west-1
dst_cid                   us-west-1
flow                            300
total                            76
weight                     3.947368
Name: 0, dtype: object
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 529, in handleProxyLoad
    temp_df = verify_return_df(temp_df, region)
  File "/app/global_controller.py", line 346, in verify_return_df
    assert False
AssertionError
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-08 06:11:16 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 953, in optimizer_entrypoint
    weight = flow / total
ZeroDivisionError: division by zero
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-08 06:11:17 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 953, in optimizer_entrypoint
    weight = flow / total
ZeroDivisionError: division by zero
__main__ - verify_return_df(line:344) - ERROR: weight is out of range. 3.9473684210526314
__main__ - verify_return_df(line:345) - row: src_svc                    frontend
dst_svc                           a
src_endpoint    frontend@GET@/start
dst_endpoint        a@POST@/spreada
src_cid                   us-west-1
dst_cid                   us-west-1
flow                            300
total                            76
weight                     3.947368
Name: 0, dtype: object
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 529, in handleProxyLoad
    temp_df = verify_return_df(temp_df, region)
  File "/app/global_controller.py", line 346, in verify_return_df
    assert False
AssertionError
__main__ - verify_return_df(line:344) - ERROR: weight is out of range. 3.9473684210526314
__main__ - verify_return_df(line:345) - row: src_svc                    frontend
dst_svc                           a
src_endpoint    frontend@GET@/start
dst_endpoint        a@POST@/spreada
src_cid                   us-west-1
dst_cid                   us-west-1
flow                            300
total                            76
weight                     3.947368
Name: 0, dtype: object
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 529, in handleProxyLoad
    temp_df = verify_return_df(temp_df, region)
  File "/app/global_controller.py", line 346, in verify_return_df
    assert False
AssertionError
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-08 06:11:18 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 953, in optimizer_entrypoint
    weight = flow / total
ZeroDivisionError: division by zero
__main__ - verify_return_df(line:344) - ERROR: weight is out of range. 3.9473684210526314
__main__ - verify_return_df(line:345) - row: src_svc                    frontend
dst_svc                           a
src_endpoint    frontend@GET@/start
dst_endpoint        a@POST@/spreada
src_cid                   us-west-1
dst_cid                   us-west-1
flow                            300
total                            76
weight                     3.947368
Name: 0, dtype: object
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 529, in handleProxyLoad
    temp_df = verify_return_df(temp_df, region)
  File "/app/global_controller.py", line 346, in verify_return_df
    assert False
AssertionError
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-08 06:11:19 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 953, in optimizer_entrypoint
    weight = flow / total
ZeroDivisionError: division by zero
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-08 06:11:20 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 953, in optimizer_entrypoint
    weight = flow / total
ZeroDivisionError: division by zero
__main__ - verify_return_df(line:344) - ERROR: weight is out of range. 3.9473684210526314
__main__ - verify_return_df(line:345) - row: src_svc                    frontend
dst_svc                           a
src_endpoint    frontend@GET@/start
dst_endpoint        a@POST@/spreada
src_cid                   us-west-1
dst_cid                   us-west-1
flow                            300
total                            76
weight                     3.947368
Name: 0, dtype: object
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 529, in handleProxyLoad
    temp_df = verify_return_df(temp_df, region)
  File "/app/global_controller.py", line 346, in verify_return_df
    assert False
AssertionError
__main__ - verify_return_df(line:344) - ERROR: weight is out of range. 3.9473684210526314
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-08 06:11:21 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 953, in optimizer_entrypoint
    weight = flow / total
ZeroDivisionError: division by zero
__main__ - verify_return_df(line:345) - row: src_svc                    frontend
dst_svc                           a
src_endpoint    frontend@GET@/start
dst_endpoint        a@POST@/spreada
src_cid                   us-west-1
dst_cid                   us-west-1
flow                            300
total                            76
weight                     3.947368
Name: 0, dtype: object
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 529, in handleProxyLoad
    temp_df = verify_return_df(temp_df, region)
  File "/app/global_controller.py", line 346, in verify_return_df
    assert False
AssertionError
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-08 06:11:22 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 953, in optimizer_entrypoint
    weight = flow / total
ZeroDivisionError: division by zero
__main__ - verify_return_df(line:344) - ERROR: weight is out of range. 3.9473684210526314
__main__ - verify_return_df(line:345) - row: src_svc                    frontend
dst_svc                           a
src_endpoint    frontend@GET@/start
dst_endpoint        a@POST@/spreada
src_cid                   us-west-1
dst_cid                   us-west-1
flow                            300
total                            76
weight                     3.947368
Name: 0, dtype: object
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 529, in handleProxyLoad
    temp_df = verify_return_df(temp_df, region)
  File "/app/global_controller.py", line 346, in verify_return_df
    assert False
AssertionError
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-08 06:11:23 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 953, in optimizer_entrypoint
    weight = flow / total
ZeroDivisionError: division by zero
__main__ - verify_return_df(line:344) - ERROR: weight is out of range. 3.9473684210526314
__main__ - verify_return_df(line:345) - row: src_svc                    frontend
dst_svc                           a
src_endpoint    frontend@GET@/start
dst_endpoint        a@POST@/spreada
src_cid                   us-west-1
dst_cid                   us-west-1
flow                            300
total                            76
weight                     3.947368
Name: 0, dtype: object
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 529, in handleProxyLoad
    temp_df = verify_return_df(temp_df, region)
  File "/app/global_controller.py", line 346, in verify_return_df
    assert False
AssertionError
__main__ - verify_return_df(line:344) - ERROR: weight is out of range. 3.9473684210526314
__main__ - verify_return_df(line:345) - row: src_svc                    frontend
dst_svc                           a
src_endpoint    frontend@GET@/start
dst_endpoint        a@POST@/spreada
src_cid                   us-west-1
dst_cid                   us-west-1
flow                            300
total                            76
weight                     3.947368
Name: 0, dtype: object
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 529, in handleProxyLoad
    temp_df = verify_return_df(temp_df, region)
  File "/app/global_controller.py", line 346, in verify_return_df
    assert False
AssertionError
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-08 06:11:24 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 953, in optimizer_entrypoint
    weight = flow / total
ZeroDivisionError: division by zero
__main__ - verify_return_df(line:344) - ERROR: weight is out of range. 3.9473684210526314
__main__ - verify_return_df(line:345) - row: src_svc                    frontend
dst_svc                           a
src_endpoint    frontend@GET@/start
dst_endpoint        a@POST@/spreada
src_cid                   us-west-1
dst_cid                   us-west-1
flow                            300
total                            76
weight                     3.947368
Name: 0, dtype: object
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 529, in handleProxyLoad
    temp_df = verify_return_df(temp_df, region)
  File "/app/global_controller.py", line 346, in verify_return_df
    assert False
AssertionError
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-08 06:11:25 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 953, in optimizer_entrypoint
    weight = flow / total
ZeroDivisionError: division by zero
