__main__ - training_phase(line:1376) - ERROR: The file trace.csv does not exist.
__main__ - training_phase(line:1377) - @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
__main__ - optimizer_entrypoint(line:879) - !!! Skip optimizer !!! root_node_rps of all callgraph in all region is 0
__main__ - optimizer_entrypoint(line:879) - !!! Skip optimizer !!! root_node_rps of all callgraph in all region is 0
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-06 21:27:41 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 953, in optimizer_entrypoint
    weight = flow / total
ZeroDivisionError: division by zero
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(613) > total capcity(600)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 316
__main__ - optimizer_entrypoint(line:891) - !!! ERROR !!! Total demand(602) > total capcity(600)
__main__ - optimizer_entrypoint(line:892) - max_capacity_per_service[a][us-west-1]: 300
__main__ - optimizer_entrypoint(line:894) - new_capacity,a, 300 -> 311
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-06 21:28:42 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 953, in optimizer_entrypoint
    weight = flow / total
ZeroDivisionError: division by zero
