global_controller - log_exception(line:838) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 576, in handleProxyLoad
    _, csv_string =  local_and_failover_routing_rule(svc, region)
  File "/app/global_controller.py", line 193, in local_and_failover_routing_rule
    dst_cid_list = svc_to_placement[dst_svc] # west only
KeyError: 'frontend'
global_controller - log_exception(line:838) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 576, in handleProxyLoad
    _, csv_string =  local_and_failover_routing_rule(svc, region)
  File "/app/global_controller.py", line 193, in local_and_failover_routing_rule
    dst_cid_list = svc_to_placement[dst_svc] # west only
KeyError: 'cartservice'
global_controller - log_exception(line:838) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 576, in handleProxyLoad
    _, csv_string =  local_and_failover_routing_rule(svc, region)
  File "/app/global_controller.py", line 193, in local_and_failover_routing_rule
    dst_cid_list = svc_to_placement[dst_svc] # west only
KeyError: 'frontend'
