global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'handleProxyLoad' did not return a valid response. The function either returned None or ended without a return statement.
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 532, in handleProxyLoad
    logger.info(f"Enforcement, {ROUTING_RULE}, optimizer_cnt-{optimizer_cnt}, {svc} in {region}, {csv_string.strip()}")
AttributeError: 'NoneType' object has no attribute 'strip'
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 517, in handleProxyLoad
    if svc == "frontend" and not percentage_df.empty:
AttributeError: 'NoneType' object has no attribute 'empty'
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 532, in handleProxyLoad
    logger.info(f"Enforcement, {ROUTING_RULE}, optimizer_cnt-{optimizer_cnt}, {svc} in {region}, {csv_string.strip()}")
AttributeError: 'NoneType' object has no attribute 'strip'
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 532, in handleProxyLoad
    logger.info(f"Enforcement, {ROUTING_RULE}, optimizer_cnt-{optimizer_cnt}, {svc} in {region}, {csv_string.strip()}")
AttributeError: 'NoneType' object has no attribute 'strip'
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 517, in handleProxyLoad
    if svc == "frontend" and not percentage_df.empty:
AttributeError: 'NoneType' object has no attribute 'empty'
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 532, in handleProxyLoad
    logger.info(f"Enforcement, {ROUTING_RULE}, optimizer_cnt-{optimizer_cnt}, {svc} in {region}, {csv_string.strip()}")
AttributeError: 'NoneType' object has no attribute 'strip'
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 532, in handleProxyLoad
    logger.info(f"Enforcement, {ROUTING_RULE}, optimizer_cnt-{optimizer_cnt}, {svc} in {region}, {csv_string.strip()}")
AttributeError: 'NoneType' object has no attribute 'strip'
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 532, in handleProxyLoad
    logger.info(f"Enforcement, {ROUTING_RULE}, optimizer_cnt-{optimizer_cnt}, {svc} in {region}, {csv_string.strip()}")
AttributeError: 'NoneType' object has no attribute 'strip'
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 517, in handleProxyLoad
    if svc == "frontend" and not percentage_df.empty:
AttributeError: 'NoneType' object has no attribute 'empty'
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 532, in handleProxyLoad
    logger.info(f"Enforcement, {ROUTING_RULE}, optimizer_cnt-{optimizer_cnt}, {svc} in {region}, {csv_string.strip()}")
AttributeError: 'NoneType' object has no attribute 'strip'
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 532, in handleProxyLoad
    logger.info(f"Enforcement, {ROUTING_RULE}, optimizer_cnt-{optimizer_cnt}, {svc} in {region}, {csv_string.strip()}")
AttributeError: 'NoneType' object has no attribute 'strip'
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 517, in handleProxyLoad
    if svc == "frontend" and not percentage_df.empty:
AttributeError: 'NoneType' object has no attribute 'empty'
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 532, in handleProxyLoad
    logger.info(f"Enforcement, {ROUTING_RULE}, optimizer_cnt-{optimizer_cnt}, {svc} in {region}, {csv_string.strip()}")
AttributeError: 'NoneType' object has no attribute 'strip'
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 532, in handleProxyLoad
    logger.info(f"Enforcement, {ROUTING_RULE}, optimizer_cnt-{optimizer_cnt}, {svc} in {region}, {csv_string.strip()}")
AttributeError: 'NoneType' object has no attribute 'strip'
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 532, in handleProxyLoad
    logger.info(f"Enforcement, {ROUTING_RULE}, optimizer_cnt-{optimizer_cnt}, {svc} in {region}, {csv_string.strip()}")
AttributeError: 'NoneType' object has no attribute 'strip'
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 517, in handleProxyLoad
    if svc == "frontend" and not percentage_df.empty:
AttributeError: 'NoneType' object has no attribute 'empty'
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 532, in handleProxyLoad
    logger.info(f"Enforcement, {ROUTING_RULE}, optimizer_cnt-{optimizer_cnt}, {svc} in {region}, {csv_string.strip()}")
AttributeError: 'NoneType' object has no attribute 'strip'
__main__ - filter_incomplete_traces(line:1302) - !!! ERROR: len(complete_traces[us-east-1]) == 0
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 517, in handleProxyLoad
    if svc == "frontend" and not percentage_df.empty:
AttributeError: 'NoneType' object has no attribute 'empty'
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 517, in handleProxyLoad
    if svc == "frontend" and not percentage_df.empty:
AttributeError: 'NoneType' object has no attribute 'empty'
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 517, in handleProxyLoad
    if svc == "frontend" and not percentage_df.empty:
AttributeError: 'NoneType' object has no attribute 'empty'
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 517, in handleProxyLoad
    if svc == "frontend" and not percentage_df.empty:
AttributeError: 'NoneType' object has no attribute 'empty'
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 517, in handleProxyLoad
    if svc == "frontend" and not percentage_df.empty:
AttributeError: 'NoneType' object has no attribute 'empty'
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 517, in handleProxyLoad
    if svc == "frontend" and not percentage_df.empty:
AttributeError: 'NoneType' object has no attribute 'empty'
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 517, in handleProxyLoad
    if svc == "frontend" and not percentage_df.empty:
AttributeError: 'NoneType' object has no attribute 'empty'
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 517, in handleProxyLoad
    if svc == "frontend" and not percentage_df.empty:
AttributeError: 'NoneType' object has no attribute 'empty'
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 517, in handleProxyLoad
    if svc == "frontend" and not percentage_df.empty:
AttributeError: 'NoneType' object has no attribute 'empty'
global_controller - log_exception(line:828) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 517, in handleProxyLoad
    if svc == "frontend" and not percentage_df.empty:
AttributeError: 'NoneType' object has no attribute 'empty'
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1383) > total capcity(1200)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-east-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 701
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1383) > total capcity(1301)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-west-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 701
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-04 06:30:26 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1001, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1351) > total capcity(1200)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[b][us-east-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,b, 600 -> 685
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1351) > total capcity(1285)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[b][us-west-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,b, 600 -> 685
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1415) > total capcity(1200)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-east-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 717
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1294) > total capcity(1000)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[c][us-west-1]: 1000
__main__ - optimizer_entrypoint(line:889) - new_capacity,c, 1000 -> 1304
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1415) > total capcity(1317)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-west-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 717
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1447) > total capcity(1200)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-east-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 733
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1447) > total capcity(1333)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-west-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 733
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1378) > total capcity(1200)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-east-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 699
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1217) > total capcity(1200)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[b][us-east-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,b, 600 -> 618
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1369) > total capcity(1000)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[c][us-west-1]: 1000
__main__ - optimizer_entrypoint(line:889) - new_capacity,c, 1000 -> 1379
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1378) > total capcity(1299)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-west-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 699
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-04 06:30:30 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1001, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1217) > total capcity(1200)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-east-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 618
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1224) > total capcity(1200)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[b][us-east-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,b, 600 -> 622
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1466) > total capcity(1000)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[c][us-west-1]: 1000
__main__ - optimizer_entrypoint(line:889) - new_capacity,c, 1000 -> 1476
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1224) > total capcity(1222)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[b][us-west-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,b, 600 -> 622
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-04 06:30:31 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1001, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1271) > total capcity(1200)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-east-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 645
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1427) > total capcity(1000)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[c][us-west-1]: 1000
__main__ - optimizer_entrypoint(line:889) - new_capacity,c, 1000 -> 1437
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1271) > total capcity(1245)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-west-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 645
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1359) > total capcity(1200)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-east-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 689
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1463) > total capcity(1000)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[c][us-west-1]: 1000
__main__ - optimizer_entrypoint(line:889) - new_capacity,c, 1000 -> 1473
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1359) > total capcity(1289)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-west-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 689
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1564) > total capcity(1000)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[c][us-west-1]: 1000
__main__ - optimizer_entrypoint(line:889) - new_capacity,c, 1000 -> 1574
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-04 06:30:35 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1001, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1429) > total capcity(1200)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-east-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 724
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1429) > total capcity(1324)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-west-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 724
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1277) > total capcity(1200)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-east-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 648
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1227) > total capcity(1000)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[c][us-west-1]: 1000
__main__ - optimizer_entrypoint(line:889) - new_capacity,c, 1000 -> 1237
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1277) > total capcity(1248)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-west-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 648
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1375) > total capcity(1200)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-east-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 697
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1375) > total capcity(1297)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-west-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 697
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1327) > total capcity(1200)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-east-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 673
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1136) > total capcity(1000)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[c][us-west-1]: 1000
__main__ - optimizer_entrypoint(line:889) - new_capacity,c, 1000 -> 1146
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1327) > total capcity(1273)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-west-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 673
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-04 06:30:39 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1001, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1390) > total capcity(1200)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-east-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 705
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1390) > total capcity(1305)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-west-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 705
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1300) > total capcity(1200)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-east-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 660
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1398) > total capcity(1000)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[c][us-west-1]: 1000
__main__ - optimizer_entrypoint(line:889) - new_capacity,c, 1000 -> 1408
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1300) > total capcity(1260)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-west-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 660
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1355) > total capcity(1200)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-east-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 687
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1355) > total capcity(1287)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-west-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 687
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1392) > total capcity(1200)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-east-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 706
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1193) > total capcity(1000)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[c][us-west-1]: 1000
__main__ - optimizer_entrypoint(line:889) - new_capacity,c, 1000 -> 1203
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1392) > total capcity(1306)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-west-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 706
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1264) > total capcity(1200)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-east-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 642
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1264) > total capcity(1242)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-west-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 642
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-04 06:30:44 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1001, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1245) > total capcity(1200)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-east-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 632
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1219) > total capcity(1000)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[c][us-west-1]: 1000
__main__ - optimizer_entrypoint(line:889) - new_capacity,c, 1000 -> 1229
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1245) > total capcity(1232)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-west-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 632
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1220) > total capcity(1200)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-east-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 620
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-04 06:30:46 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1001, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1022) > total capcity(1000)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[c][us-west-1]: 1000
__main__ - optimizer_entrypoint(line:889) - new_capacity,c, 1000 -> 1032
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1154) > total capcity(1000)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[c][us-west-1]: 1000
__main__ - optimizer_entrypoint(line:889) - new_capacity,c, 1000 -> 1164
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1202) > total capcity(1200)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-east-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 611
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1216) > total capcity(1200)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-east-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 618
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1117) > total capcity(1000)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[c][us-west-1]: 1000
__main__ - optimizer_entrypoint(line:889) - new_capacity,c, 1000 -> 1127
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1116) > total capcity(1000)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[c][us-west-1]: 1000
__main__ - optimizer_entrypoint(line:889) - new_capacity,c, 1000 -> 1126
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1044) > total capcity(1000)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[c][us-west-1]: 1000
__main__ - optimizer_entrypoint(line:889) - new_capacity,c, 1000 -> 1054
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-04 06:30:56 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1001, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1201) > total capcity(1200)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-east-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 610
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1136) > total capcity(1000)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[c][us-west-1]: 1000
__main__ - optimizer_entrypoint(line:889) - new_capacity,c, 1000 -> 1146
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1204) > total capcity(1200)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-east-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 612
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-04 06:30:58 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1001, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1122) > total capcity(1000)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[c][us-west-1]: 1000
__main__ - optimizer_entrypoint(line:889) - new_capacity,c, 1000 -> 1132
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1273) > total capcity(1200)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-east-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 646
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1273) > total capcity(1246)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-west-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 646
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1155) > total capcity(1000)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[c][us-west-1]: 1000
__main__ - optimizer_entrypoint(line:889) - new_capacity,c, 1000 -> 1165
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-04 06:31:09 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 1001, in optimizer_entrypoint
    assert False # TODO: not implemented yet
AssertionError
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1307) > total capcity(1000)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[c][us-west-1]: 1000
__main__ - optimizer_entrypoint(line:889) - new_capacity,c, 1000 -> 1317
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1152) > total capcity(1000)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[c][us-west-1]: 1000
__main__ - optimizer_entrypoint(line:889) - new_capacity,c, 1000 -> 1162
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1216) > total capcity(1200)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-east-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 618
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1232) > total capcity(1000)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[c][us-west-1]: 1000
__main__ - optimizer_entrypoint(line:889) - new_capacity,c, 1000 -> 1242
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1307) > total capcity(1200)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-east-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 663
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1307) > total capcity(1263)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-west-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 663
__main__ - optimizer_entrypoint(line:886) - !!! ERROR !!! Total demand(1207) > total capcity(1200)
__main__ - optimizer_entrypoint(line:887) - max_capacity_per_service[a][us-east-1]: 600
__main__ - optimizer_entrypoint(line:889) - new_capacity,a, 600 -> 613
